document.writeln("		<div align=\"right\">");
document.writeln("			<nav>");
document.writeln("   	 		<ul>");
document.writeln("   	     		<li><a href=\"../en/index.html\">English</a></li>");
document.writeln("     	   		<li><a href=\"../cn/index.html\">中文</a></li>");
document.writeln("    			</ul>");
document.writeln("			</nav>");
document.writeln("		</div>");
document.writeln("		<nav>");
document.writeln("    		<ul>");
document.writeln("        		<li><a href=\"../cn/index.html\">主页</a></li>");
document.writeln("        		<li><a href=\"talks.html\">学术报告</a></li>");
document.writeln("        		<li><a href=\"doc.html\">文档</a></li>");
document.writeln("    		</ul>");
document.writeln("		</nav>");